""""
this code is to generate scatter plots for absolute values of wuantities averaged across all frames of the video, 
for each class and each percentile. The quantities are read from the .npy files generated by the script `var_class_temporal_series.py`
and scatter plots are generated for variable pairs:

- mean lightning counts 
- mean precipitation cumulated over 30 min

- mean non zero lightning counts
- mean precipitation cumulated over 30 min

possible variables to read are
For `euclid_msg_grid`:
- For each class and frame, the script computes:
    - `lightning_count`: mean over all samples
    - `lightning_count_std`: standard deviation over all samples
    - `lightning_nonzero_fraction`: fraction of samples with count `> 0`
    - `lightning_mean_nonzero`: mean computed only on samples where count `> 0`
- This separates occurrence from intensity:
    - `lightning_nonzero_fraction` tells how often lightning is present
    - `lightning_mean_nonzero` tells how strong it is when it is present


For `precipitation`:
- The script computes, for each class and frame:
    - the mean and standard deviation of `50`
    - the mean and standard deviation of `95`
    - the mean and standard deviation of `sum[mm]`
    - the mean and standard deviation of `prec_fraction`


"""""


import os
import matplotlib.pyplot as plt
import numpy as np
import sys  


# Add the repository root so top-level packages such as `utils` resolve
# regardless of the directory from which this script is launched.
REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
if REPO_ROOT not in sys.path:
    sys.path.append(REPO_ROOT)  

sys.path.append(os.path.abspath("/Users/claudia/Documents/ML-postprocessing"))
from utils.plotting.class_colors import colors_per_class1_names, class_groups   
from gradients_across_frames import read_gradient_files, read_named_gradient_series


def main():
    
    output_dir = '/sat_data/output/grl_2026/figs/'

    # read as arrays the content of the .py files with mean gradients for each class and each percentile
    file_path_cot = os.path.join(output_dir, f'mean_gradients_cot.npy')
    file_path_cth = os.path.join(output_dir, f'mean_gradients_cth.npy')
    file_path_cma = os.path.join(output_dir, f'mean_gradients_cma.npy')


    mean_grad_class_cot = read_gradient_files(file_path_cot)
    mean_grad_class_cth = read_gradient_files(file_path_cth)
    mean_grad_class_cma = read_gradient_files(file_path_cma)
    mean_precip_sum = read_named_gradient_series(
        'precipitation',
        'sum[mm]',
        output_dir,
    )
    mean_count_lightning = read_named_gradient_series(
        'euclid_msg_grid',
        'lightning_count',
        output_dir,
    )

    # calculate mean value for the time series of precipitation sum and lightning count for each class
    mean_precip_sum_class = mean_precip_sum.mean(axis=1)
    mean_count_lightning_class = mean_count_lightning.mean(axis=1)

