""""
this code is to generate scatter plots for absolute values of quantities averaged across all frames of the video, 
for each class. The quantities are read from the .npy or csv files generated by the script `var_class_temporal_series.py`
and scatter plots are generated for variable pairs:

- conditional mean lightning counts 
- conditional mean precipitation cumulated over 30 min

- mean non zero lightning counts
- mean precipitation cumulated over 30 min

Author: Claudia Acquistapace
Date: 5 june 2026
github: ML_postprocessing

"""""


import os
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import numpy as np
import pandas as pd
import sys  
import pdb

# Add the repository root so top-level packages such as `utils` resolve
# regardless of the directory from which this script is launched.
REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
if REPO_ROOT not in sys.path:
    sys.path.append(REPO_ROOT)  

sys.path.append(os.path.abspath("/Users/claudia/Documents/ML-postprocessing"))
from utils.plotting.class_colors import colors_per_class1_names, class_groups   

TRAIN_MARKER = "o"
TEST_MARKER = "^"
MARKER_SIZE = 100
LEGEND_GREY = "0.4"


def read_csv_file(file_path):
    df = pd.read_csv(file_path)
    return df


def read_mean_series_files(input_dir, suffix=""):
    """Read mean time-series summary CSVs for either training or test."""
    file_path_precipitation = os.path.join(input_dir, f'mean_values_of_series_precipitation{suffix}.csv')
    file_path_euclid_msg_grid = os.path.join(input_dir, f'mean_values_of_series_euclid_msg_grid{suffix}.csv')
    file_path_cma = os.path.join(input_dir, f'mean_values_of_series_cma{suffix}.csv')

    return {
        "precipitation": read_csv_file(file_path_precipitation),
        "euclid_msg_grid": read_csv_file(file_path_euclid_msg_grid),
        "cma": read_csv_file(file_path_cma),
    }


def get_value_for_label(df, label, column_name):
    """Return the scalar value for a class label and column, or None when unavailable."""
    rows = df[df["label"] == int(label)]
    if rows.empty or column_name not in rows:
        return None
    value = rows.iloc[0][column_name]
    if pd.isna(value):
        return None
    return value


def get_available_class_labels(*dataframes):
    labels = set()
    for df in dataframes:
        labels.update(df["label"].dropna().astype(int).tolist())
    return sorted(label for label in labels if str(label) in colors_per_class1_names)


def style_scatter_axis(ax):
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_linewidth(1.5)
    ax.spines['bottom'].set_linewidth(1.5)
    ax.grid(color='lightgray', linestyle='--', linewidth=0.5)


def add_color_and_symbol_legends(ax, class_labels):
    class_handles = [
        Line2D(
            [0],
            [0],
            marker='o',
            linestyle='None',
            markerfacecolor=colors_per_class1_names[str(label)],
            markeredgecolor=colors_per_class1_names[str(label)],
            markersize=8,
            label=f'Class {label}',
        )
        for label in class_labels
    ]
    class_legend = ax.legend(handles=class_handles, frameon=False, title="Classes", loc="best")
    ax.add_artist(class_legend)

    split_handles = [
        Line2D(
            [0],
            [0],
            marker=TRAIN_MARKER,
            linestyle='None',
            markerfacecolor=LEGEND_GREY,
            markeredgecolor=LEGEND_GREY,
            markersize=8,
            label='Training',
        ),
        Line2D(
            [0],
            [0],
            marker=TEST_MARKER,
            linestyle='None',
            markerfacecolor=LEGEND_GREY,
            markeredgecolor=LEGEND_GREY,
            markersize=8,
            label='Testing',
        ),
    ]
    ax.legend(handles=split_handles, frameon=False, title="Dataset", loc="upper left")


def scatter_train_test_by_class(ax, train_frames, test_frames, x_source, y_source, x_column, y_column):
    class_labels = get_available_class_labels(
        train_frames[x_source],
        train_frames[y_source],
        test_frames[x_source],
        test_frames[y_source],
    )

    for class_number in class_labels:
        class_color = colors_per_class1_names[str(class_number)]
        print(f"Processing class {class_number} with color {class_color}")

        train_x = get_value_for_label(train_frames[x_source], class_number, x_column)
        train_y = get_value_for_label(train_frames[y_source], class_number, y_column)
        if train_x is not None and train_y is not None:
            ax.scatter(
                train_x,
                train_y,
                color=class_color,
                s=MARKER_SIZE,
                marker=TRAIN_MARKER,
            )

        test_x = get_value_for_label(test_frames[x_source], class_number, x_column)
        test_y = get_value_for_label(test_frames[y_source], class_number, y_column)
        if test_x is not None and test_y is not None:
            ax.scatter(
                test_x,
                test_y,
                color=class_color,
                s=MARKER_SIZE,
                marker=TEST_MARKER,
            )

    return class_labels


def main():
    
    # define output directory for plots
    output_dir = '/sat_data/output/grl_2026/figs/'

    # define input directory for .csv files with mean gradients and mean values of the time series for each class
    input_dir = '/sat_data/output/grl_2026/npz/'

    train_frames = read_mean_series_files(input_dir)
    test_frames = read_mean_series_files(input_dir, suffix="_test")

    # generate scatter plots for variable pairs
    # 1. Scatter plot of conditional mean count of lightning vs conditional mean cumulated prec over 30 min [mm]
    fig, ax = plt.subplots(figsize=(8, 6))
    class_labels = scatter_train_test_by_class(
        ax,
        train_frames,
        test_frames,
        x_source="precipitation",
        y_source="euclid_msg_grid",
        x_column="sum[mm]_temporal_mean",
        y_column="lightning_mean_nonzero_temporal_mean",
    )

    style_scatter_axis(ax)
    ax.set_xlabel('Conditional mean cumulated prec over 30 min [mm]')
    ax.set_ylabel('Conditional mean count of lightning')
    ax.set_title('Scatter plot of conditional mean count \n of lightning vs conditional mean cumulated prec over 30 min [mm]')
    add_color_and_symbol_legends(ax, class_labels)
    fig.tight_layout()
    fig.savefig(os.path.join(output_dir, f'scatter_cond_mean_lightning_vs_cond_mean_precipitation.png'), dpi=300)
    plt.close(fig)


    # 2. Scatter plot of cma vs prec fraction

    fig, ax = plt.subplots(figsize=(8, 6))
    class_labels = scatter_train_test_by_class(
        ax,
        train_frames,
        test_frames,
        x_source="precipitation",
        y_source="cma",
        x_column="prec_fraction_temporal_mean",
        y_column="categorical_temporal_mean",
    )

    style_scatter_axis(ax)
    ax.set_xlabel('Precipitation fraction')
    ax.set_ylabel('Cloud cover mean value')
    ax.set_title('Scatter plot of cloud cover mean value vs precipitation fraction')
    add_color_and_symbol_legends(ax, class_labels)
    fig.tight_layout()
    fig.savefig(os.path.join(output_dir, f'scatter_cloud_cover_vs_precipitation_fraction.png'), dpi=300)
    plt.close(fig)

if __name__ == "__main__":
    main()
