""""
this code is to generate scatter plots for absolute values of quantities averaged across all frames of the video, 
for each class. The quantities are read from the .npy or csv files generated by the script `var_class_temporal_series.py`
and scatter plots are generated for variable pairs:

- conditional mean lightning counts 
- conditional mean precipitation cumulated over 30 min

- mean non zero lightning counts
- mean precipitation cumulated over 30 min

Author: Claudia Acquistapace
Date: 5 june 2026
github: ML_postprocessing

"""""


import os
import matplotlib.pyplot as plt
import numpy as np
import sys  
import pdb

# Add the repository root so top-level packages such as `utils` resolve
# regardless of the directory from which this script is launched.
REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
if REPO_ROOT not in sys.path:
    sys.path.append(REPO_ROOT)  

sys.path.append(os.path.abspath("/Users/claudia/Documents/ML-postprocessing"))
from utils.plotting.class_colors import colors_per_class1_names, class_groups   


def read_csv_file(file_path):
    import pandas as pd
    df = pd.read_csv(file_path)
    return df


def main():
    
    # define output directory for plots
    output_dir = '/sat_data/output/grl_2026/figs/'

    # define input directory for .csv files with mean gradients and mean values of the time series for each class
    input_dir = '/sat_data/output/grl_2026/npz/'

    # read as arrays the content of the .py files with mean gradients for each class and each percentile
    file_path_precipitation = os.path.join(input_dir, f'mean_values_of_series_precipitation.csv')
    file_path_euclid_msg_grid = os.path.join(input_dir, f'mean_values_of_series_euclid_msg_grid.csv')
    file_path_cma = os.path.join(input_dir, f'mean_values_of_series_cma.csv')
    file_path_cot = os.path.join(input_dir, f'mean_values_of_series_cot.csv')

    # read csv files
    df_precipitation = read_csv_file(file_path_precipitation)
    df_euclid_msg_grid = read_csv_file(file_path_euclid_msg_grid)   
    df_cma = read_csv_file(file_path_cma)
    df_cot = read_csv_file(file_path_cot)


    # read variables of interest from the .csv files
    # from precipitation file, read conditional mean sum[mm] precipitation and prec_fraction
    cond_prec_mean_sum_precipitation = df_precipitation['sum[mm]_temporal_mean']
    prec_fraction = df_precipitation['prec_fraction_temporal_mean']
    # from euclid_msg_grid file, read conditional mean count of lightning and lightning_fraction
    cond_mean_count_lightning = df_euclid_msg_grid['lightning_count_temporal_mean']
    count_non_zero_lightning = df_euclid_msg_grid['lightning_mean_nonzero_temporal_mean']
    # from cma
    mean_cma = df_cma['categorical_temporal_mean']

    # generate scatter plots for variable pairs
    from utils.plotting.class_colors import colors_per_class1_names, class_groups

    # 1. Scatter plot of conditional mean count of lightning vs conditional mean cumulated prec over 30 min [mm]
    plt.figure(figsize=(8, 6))

    # loop on class groups and plot distributions for each class in the group in the same plot
    # crop colors_per_class1_names to 8 classes
    colors_per_class1_names_cropped = {k: v for k, v in colors_per_class1_names.items() if int(k) < 8}

    for class_number, class_color in colors_per_class1_names.items():

        # select the value of the dataframe corresponding to the class number in the class group from the columns
        class_rows_precipitation = cond_prec_mean_sum_precipitation[int(class_number)]
        class_rows_euclid_msg_grid = count_non_zero_lightning[int(class_number)]

        # pick the color associate to the class_id of the class group
        class_color = colors_per_class1_names[class_number]   

        print(f"Processing class group: {class_number} with color {class_color}")
        # plot round large bullets with the color of the class group
        plt.scatter(class_rows_precipitation, 
                    class_rows_euclid_msg_grid, 
                    c=class_color,
                     s=100, 
                     label=f'Class {class_number}')

    # remove upper and right spines and make remaining thicker
    ax = plt.gca()
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_linewidth(1.5)
    ax.spines['bottom'].set_linewidth(1.5)
    
    plt.xlabel('Conditional mean cumulated prec over 30 min [mm]')
    plt.ylabel('Conditional mean count of lightning')
    plt.title('Scatter plot of conditional mean count \n of lightning vs conditional mean cumulated prec over 30 min [mm]')
    plt.grid(color='lightgray', linestyle='--', linewidth=0.5)
    plt.legend(frameon=False)
    plt.savefig(os.path.join(output_dir, f'scatter_cond_mean_lightning_vs_cond_mean_precipitation.png'), dpi=300)
    plt.close()


    # 2. Scatter plot of cma vs prec fraction

    plt.figure(figsize=(8, 6))

    # loop on class groups and plot distributions for each class in the group in the same plot
    # crop colors_per_class1_names to 8 classes
    colors_per_class1_names_cropped = {k: v for k, v in colors_per_class1_names.items() if int(k) < 8}

    for class_number, class_color in colors_per_class1_names.items():

        # select the value of the dataframe corresponding to the class number in the class group from the columns
        class_rows_precipitation = prec_fraction[int(class_number)]
        class_rows_cma = mean_cma[int(class_number)]

        # pick the color associate to the class_id of the class group
        class_color = colors_per_class1_names[class_number]   

        print(f"Processing class group: {class_number} with color {class_color}")
        # plot round large bullets with the color of the class group
        plt.scatter(class_rows_precipitation, 
                    class_rows_cma, 
                    c=class_color,
                     s=100, 
                     label=f'Class {class_number}')

    # remove upper and right spines and make remaining thicker
    ax = plt.gca()
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_linewidth(1.5)
    ax.spines['bottom'].set_linewidth(1.5)
    
    plt.xlabel('Precipitation fraction')
    plt.ylabel('Cloud cover mean value')
    plt.title('Scatter plot of cloud cover mean value vs precipitation fraction')
    plt.grid(color='lightgray', linestyle='--', linewidth=0.5)
    plt.legend(frameon=False)
    plt.savefig(os.path.join(output_dir, f'scatter_cloud_cover_vs_precipitation_fraction.png'), dpi=300)
    plt.close()

if __name__ == "__main__":
    main()
