# ==========================
# Experiment Configuration
# ==========================
experiment:
  run_names: #add mulitple names in case a comparison has to be done (like chacking loss)
    - grl_2026_k10
    #- dcv2_ir108-cm_100x100_8frames_k9_70k_nc_r2dplus1
    #- dcv2_ir108_ot_100x100_k9_35k_nc_vit
  epoch: 800          # Epoch number for the main run
  random_state: 3     # Random seed for reproducibility (tsne, sampling selection, training_run)
  base_path: /sat_data/runs
  path_out: /sat_data/fig #/data1/fig
  from_crop_stats: True  # Use crop stats file instead of crop list file
  crop_resolution: 100x100 # resolution of the crops, used for naming the output files
  n_frames: 8 # number of frames in the crops, used for naming the output files
  backbone: r2dplus1 # backbone used for the features, used for naming the output files
  n_input_layers: 1_cm # 1 channel with cloud mask applied
logging:  
  logs_path: /home/claudia/codes/ML_postprocessing/logs
  log_level: INFO


# ==========================
# Dimensionality Reduction
# can be expanded, if many dim reduction methods will be implemented, consider creating a separate config for it
# ==========================
reduction:
  epochs: [800] # Feature checkpoints to embed. Each listed epoch triggers a separate reduction run.
  feature_folder: /sat_data/runs/grl_2026_k10/features/epoch_800/ # /sat_data/runs/grl_2026/features/epoch_800/
  output_path: /sat_data/fig/grl_2026_k10/
  filename_suffix: ""
  random_states: [3] # Random seeds for the reduction. Each listed seed triggers a separate reduction run.
  n_crops: 25368
  sampling_type: all   # Options: random, closest, farthest, all
  methods: [tsne_opentsne]
  method: tsne            # Options: tsne, isomap, etc., 
  perplexity: 50
  isomap: {
    n_neighbors: 10,
    n_components: 2
    }
  tsne_sklearn: {
    n_components: 2,
    perplexity: 30,
    n_iter: 1000,
    learning_rate: 200
    }
  tsne_opentsne: {
    perplexity: 50, 
    initialization: "pca",
    metric: cosine
  }


# ==========================
# Preparation of features samples (CSV files)
# ==========================
features_preparation:
  video: True # keyword to modify features preparation in case of videos
  crops_path: /sat_data/crops/grl_2026/1/ # path to the crops, used to extract the timestamps for the CSV file
  base_path: /sat_data/runs
  images_path: /sat_data/crops/grl_2026/img/ # path to images of the crops, used for visualization and metadata in the CSV file
  output_path: /sat_data/output/grl_2026_k10/csv/ #/data1/fig/grl_2026/
  n_dim: 128
  feature_file_train_inds: rank0_chunk0_train_heads_inds.npy
  feature_file_train_features: rank0_chunk0_train_heads_features.npy
  feature_file_test_inds: rank0_chunk0_train_heads_inds.npy
  feature_file_test_features: rank0_chunk0_train_heads_features.npy
  crops_test_path: /sat_data/crops/GRL_testing_crops/ # path to the test crops, used for visualization and metadata in the CSV file
  images_test_path: /sat_data/crops/GRL_testing_crops/ # path to images of the test crops, used for visualization and metadata in the CSV file
# ==========================
# Data / Crops Configuration / Sampling Configuration
# ==========================
data:
  data_base_path: /sat_data/crops #/data1/crops
  crops_name: grl_2026/1/ #clips_ir108_100x100_8frames_2013-2020 # name of the dataset, TODO implement the case with more runs
  file_extension: nc   # Options: nc, tif
  nc_engine: netcdf4   #engine for xarray, choose between {"netcdf4", "scipy", "pydap", "h5netcdf", "zarr", None}
  sampling_type: all   # Options: random, closest, farthest, all
  n_subsample: 1000 #70072   # Max samples per cluster. TODO: if 'all', use all samples without specifying here
  filter_daytime: false  # Keep only 06–16 UTC
  filter_imerg: true    # Keep only timestamps at minutes 00 or 30, as IMERG product (set to true only if precipitation is used and n_frames==1)
  n_frames: 8 # Number of frames to consider for each crop
  benchmark_block_size: 250   # Number of samples to process in each day block, processing in chunks needed to avod out of memory (OOM) errors with large datasets
  feature_csv_path: /sat_data/output/grl_2026_k10/csv/features_grl_2026_k10.csv # Path to the CSV file where the features will be saved, used for visualization and metadata in the CSV file

# ==========================
# Cloud motion
# ==========================
cloud_motion:
  mode: train
  crop_dir: /sat_data/crops/grl_2026/1/
  csv:
  output_file_key: training_cloud_motion
  path_column: path
  label_column: label
  video_summary_key: training_video_summary
  summary_crop_column: crop
  summary_label_column: label
  variable: IR_108
  nc_engine: netcdf4
  limit:
  pixel_size_km: 3
  frame_interval_minutes: 15
  invalid_value:
  min_valid_fraction: 0.05
  max_shift_pixels:

# ==========================
# Statistics
# ==========================
statistics:
  spatial:
    sel_vars:
      - cth
      - cma
      - cot
      #- cph
      - precipitation
      - euclid_msg_grid
      #- RR
    percentiles: [50, 95, 25, 75]  # percentiles to compute (IQR can be derived from 25 and 75)
    #TODO implement something to evalaute the cloud organization (Iorg, spectral analysis, aspect_ratio, aggregation...)

    # NEW: control whether spatial metrics are per-frame or aggregated
    mode: per_frame    # compute metrics at each timestep separately (then this can be also used to check the change in time of the spatial metrics)
      #- aggregated    # collapse all frames into one distribution


  # Time-development statistics (multi-frame evolution across time dimension)
  temporal:
    enabled: true
    metrics:
      - cloud_cover_change   # ΔCC / Δt, relative CC change
      - vertical_growth      # ΔCTH / Δt, max/mean option handled in code
      - horizontal_motion    # displacement & velocity
      - motion_direction     # azimuth angle of displacement vector
    options:
      normalize_by_duration: true   # normalize Δ by total time length
      convective_ref: "max_cth"     # how to define "cloud center" (max_cth, center_of_mass, ...)
# ==========================
  # General flags
# ==========================
  include_geotime: false      # Include geospatial and temporal metadata (month, hour, lat_mid, lon_mid)
  time_dimension: true       # Global flag: whether time metrics should be computed at all
  use_parallel: false        # Parallelization (logging issue with joblib)
  n_cores: 1                 # Number of CPU cores


# ==========================
# visualization embeddings
# ==========================
visualization:
  run_name: grl_2026_k10
  crops_name: grl_2026/1/
  random_state: 3
  sampling_type: all
  reduction_method: tsne
  epochs: [800]
  file_extension: png
  substitute_path: True
  variable_type: IR_108
  video: True
  n_frames: 8
  selection: closest # Options: random, closest, farthest, all for tsne visualization, TODO implement the case with more runs
  random_seed: [16]
  vmin: -60
  center: 0
  vmax: 5
  cmap: gray_r
  output_path: /sat_data/output/grl_2026_k10/csv/ #/data1/fig/grl_2026/
  image_crops_path: /sat_data/crops/grl_2026/img/
  plot_types:
    - embedding_crops_table
    - average_crop_shapes
  embedding_path: /sat_data/fig/grl_2026_k10/tsne_opentsne_perpl-50_grl_2026_k10_3_epoch_800.npy
  crops_path: /sat_data/runs/grl_2026_k10/crops_list_epoch_800.npy



# ==========================
# output files
# ==========================
output_files:
  run_name: grl_2026_k10
  training_csv_cth10plus: /sat_data/output/grl_2026_k10/csv/crops_stats_var-cth10plus_stats-fraction_frames-8_timedim_grl_2026_k10_all_240216_imergmin.csv
  training_csv_cth: /sat_data/output/grl_2026_k10/csv/crops_stats_var-cth_stats-50-95-25-75_frames-8_timedim_grl_2026_k10_all_240216_imergmin.csv 
  training_csv_cma: /sat_data/output/grl_2026_k10/csv/crops_stats_var-cma_stats-50-95-25-75_frames-8_timedim_grl_2026_k10_all_240216_imergmin.csv 
  training_csv_cot: /sat_data/output/grl_2026_k10/csv/crops_stats_var-cot_stats-50-95-25-75_frames-8_timedim_grl_2026_k10_all_240216_imergmin.csv
  training_csv_cot30plus: /sat_data/output/grl_2026_k10/csv/crops_stats_var-cot30plus_stats-fraction_frames-8_timedim_grl_2026_k10_all_240216_imergmin.csv
  training_csv_precipitation: /sat_data/output/grl_2026_k10/csv/crops_stats_var-precipitation_stats-50-95-25-75_frames-8_timedim_grl_2026_k10_all_240216_imergmin.csv
  training_csv_euclid_msg_grid: /sat_data/output/grl_2026_k10/csv/crops_stats_var-euclid_msg_grid_stats-50-95-25-75_frames-8_timedim_grl_2026_k10_all_240216_imergmin.csv
  training_video_summary: /sat_data/output/grl_2026_k10/csv/crops_video_summary_vars-cth-cma-cot-precipitation-euclid_msg_grid-cth10plus-cot30plus_stats-mean-std-gradient_frames-8_timedim_grl_2026_k10_all_240216_imergmin.csv
  training_cloud_motion: /sat_data/output/grl_2026_k10/csv/cloud_motion_training_all.csv
  testing_video_summary: /sat_data/output/grl_2026_k10/csv/crops_video_summary_vars-cth-cma-cot-precipitation-euclid_msg_grid-cth10plus-cot30plus_stats-mean-std-gradient_frames-8_timedim_grl_2026_k10_test_all_58095_imergmin.csv
  testing_cloud_motion: /sat_data/output/grl_2026_k10/csv/cloud_motion_testing_all.csv
  testing_csv_cth10plus: /sat_data/output/grl_2026_k10/csv/crops_stats_var-cth10plus_stats-fraction_frames-8_timedim_grl_2026_k10_test_all_58095_imergmin.csv
  testing_csv_cth: /sat_data/output/grl_2026_k10/csv/crops_stats_var-cth_stats-50-95-25-75_frames-8_timedim_grl_2026_k10_test_all_58095_imergmin.csv
  testing_csv_cma: /sat_data/output/grl_2026_k10/csv/crops_stats_var-cma_stats-50-95-25-75_frames-8_timedim_grl_2026_k10_test_all_58095_imergmin.csv
  testing_csv_cot: /sat_data/output/grl_2026_k10/csv/crops_stats_var-cot_stats-50-95-25-75_frames-8_timedim_grl_2026_k10_test_all_58095_imergmin.csv
  testing_csv_cot30plus: /sat_data/output/grl_2026_k10/csv/crops_stats_var-cot30plus_stats-fraction_frames-8_timedim_grl_2026_k10_test_all_58095_imergmin.csv
  testing_csv_precipitation: /sat_data/output/grl_2026_k10/csv/crops_stats_var-precipitation_stats-50-95-25-75_frames-8_timedim_grl_2026_k10_test_all_58095_imergmin.csv
  testing_csv_euclid_msg_grid: /sat_data/output/grl_2026_k10/csv/crops_stats_var-euclid_msg_grid_stats-50-95-25-75_frames-8_timedim_grl_2026_k10_test_all_58095_imergmin.csv
  figures_dir: /sat_data/output/grl_2026_k10/figs/
  features_training: /sat_data/output/grl_2026_k10/csv/grl_2026_k10-features_backbone_r2dplus1_cropres_100x100_inputvars_1_cm_epochs_800.csv
  features_testing: /sat_data/fig/grl_2026_k10/test/features_test_dataset_ESSL_grl_2026_k10.csv
  csv_dir: /sat_data/output/grl_2026_k10/csv/

  ancillary_files:
    essl_dataset: /sat_data/output/grl_2026/csv/eswd-v2-2012-2025_expats.csv
