# ==========================
# Variables Metadata
# ==========================
variables:
  cot:
    long_name: "cloud optical thickness"
    unit: null
    categorical: false
    logscale: false
    direction: "incr"
    vmin: 0
    vmax: 50
    bucket_name: expats-cmsaf-cloud
    bucket_filename_prefix: MCP_
    bucket_filename_suffix: _regrid.nc

  cth:
    long_name: "cloud top height"
    unit: "km"
    categorical: false
    logscale: false
    direction: "incr"
    vmin: 0
    vmax: 12
    bucket_name: expats-cmsaf-cloud
    bucket_filename_prefix: MCP_
    bucket_filename_suffix: _regrid.nc

  cma:
    long_name: "cloud cover"
    unit: null
    categorical: true
    logscale: false
    direction: "incr"
    vmin: 0
    vmax: 1
    bucket_name: expats-cmsaf-cloud
    bucket_filename_prefix: MCP_
    bucket_filename_suffix: _regrid.nc

  cph:
    long_name: "ice ratio"
    unit: null
    categorical: true
    logscale: false
    direction: "incr"
    vmin: 0
    vmax: 1
    bucket_name: expats-cmsaf-cloud
    bucket_filename_prefix: MCP_
    bucket_filename_suffix: _regrid.nc

  precipitation:
    long_name: "IMERG rain rate"
    unit: "mm/h"
    categorical: true
    logscale: false
    direction: "incr"
    vmin: 0
    vmax: 20
    bucket_name: expats-imerg-prec
    bucket_filename_prefix: IMERG_daily_
    bucket_filename_suffix: .nc

  radar_prec:
    long_name: "RADAR rain rate"
    unit: "mm/h"
    categorical: true
    logscale: false
    direction: "incr"
    vmin: 0
    vmax: 20
    bucket_name: expats-radar-germany
    bucket_filename_prefix: 
    bucket_filename_suffix: _RR_15min_msg_res.nc.gz

  lightning:
    long_name: "EUCLID total lightning"
    unit: null
    categorical: true
    logscale: 
    direction: "incr"
    vmin: 
    vmax: 
    bucket_name: expats-euclid
    bucket_filename_prefix: EUCLID_total_lightning_
    bucket_filename_suffix: .nc

  hour:
    long_name: "hour"
    unit: "UTC"
    categorical: true
    logscale: false
    direction: "incr"
    vmin: 0
    vmax: 23
    bucket_name: null

  month:
    long_name: "month"
    unit: null
    categorical: true
    logscale: false
    direction: "incr"
    vmin: 4
    vmax: 9
    bucket_name: null

  lat_mid:
    long_name: "latitude middle point"
    unit: "°N"
    categorical: false
    logscale: false
    direction: "incr"
    vmin: 42
    vmax: 52
    bucket_name: null

  lon_mid:
    long_name: "longitude middle point"
    unit: "°E"
    categorical: false
    logscale: false
    direction: "incr"
    vmin: 5
    vmax: 16
    bucket_name: null
